# Generated by Django 2.0.3 on 2018-06-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_cities_country_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='activation_key',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='otp',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
